from compilerresources import CompilerResources
from compilerconfiguration import DymolaConfiguration
from compilerconfiguration import OpenModelicaConfiguration
from compilerconfiguration import  JModelicaConfiguration