function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 24-Oct-2017 21:14:57

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(plot1(1),'DisplayName','Gen1.P',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot1(2),'DisplayName','Gen2.P');
set(plot1(3),'DisplayName','Gen3.P',...
    'Color',[0.470588235294118 0.670588235294118 0.188235294117647]);

% Create xlabel
xlabel('Time (s)');

% Create ylabel
ylabel('Active Power (p.u.)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 20]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.5 2.5]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Gill Sans','FontSize',14);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southeast','FontSize',14);

